{
 "title": "Chainlink Testing Insights",
 "description": "A look at the components of Chainlink Integration tests",
 "tags": [ "tests" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "cl_node",
    "label": "Chainlink Node",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "geth_node",
    "label": "Simulated Geth Node",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Components health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Components health",
     "type": "stat",
     "description": "Components health",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "health{namespace=\"$namespace\", app=\"chainlink-0\"}",
       "legendFormat": "service: {{service_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EVM CL node metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "EVM node polls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(evm_pool_rpc_node_polls_success{namespace=\"$namespace\", app=\"chainlink-0\"} [2m])"
      }
     ]
    },
    {
     "title": "RPC calls hist",
     "type": "timeseries",
     "description": "RPC calls hist",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{pod=\"$cl_node\", rpcCallName=\"CallContext\"}[5m])) by (le)) * 1e-6"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{pod=\"$cl_node\", rpcCallName=\"CallContext\"}[5m])) by (le)) * 1e-6"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"BatchCallContext\"}[5m])) by (le)) * 1e-6"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"BatchCallContext\"}[5m])) by (le)) * 1e-6"
      }
     ]
    },
    {
     "title": "RPC node states",
     "type": "timeseries",
     "description": "RPC node states",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "evm_pool_rpc_node_states{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "chainId: {{evmChainID}} pod: {{pod}} state: {{state}}"
      }
     ]
    },
    {
     "title": "RPC node alive statuses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "evm_pool_rpc_node_num_transitions_to_alive{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "chainId: {{evmChainID}} pod: {{pod}}"
      }
     ]
    },
    {
     "title": "RPC calls total (rate)",
     "type": "timeseries",
     "description": "RPC calls total (rate)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(evm_pool_rpc_node_calls_total{namespace=\"$namespace\", pod=\"$cl_node\"}[2m])"
      }
     ]
    },
    {
     "title": "Total verifications (success/errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(evm_pool_rpc_node_verifies{namespace=\"$namespace\", pod=\"$cl_node\"} [2m])",
       "legendFormat": "Success, chainId: {{evmChainID}} nodeName: {{nodeName }} instance: {{instance}}"
      },
      {
       "expr": "rate(evm_pool_rpc_node_verifies_success{namespace=\"$namespace\", pod=\"$cl_node\"} [2m])",
       "legendFormat": "Total, chainId: {{evmChainID}} nodeName: {{nodeName }} instance: {{instance}}"
      }
     ]
    },
    {
     "title": "ETH account value",
     "type": "timeseries",
     "description": "ETH account value",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "eth_balance{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "account: {{account}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test runner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Test Runner Logs",
     "type": "logs",
     "description": "Logs of the instance actually running the tests",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"}"
      }
     ]
    },
    {
     "title": "Runner CPU",
     "type": "timeseries",
     "description": "Test Runner CPU usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"remote-test-runner\", resource=\"cpu\"}",
       "legendFormat": "Limit"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"remote-test-runner\"}",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Runner RAM",
     "type": "timeseries",
     "description": "Test Runner RAM usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"remote-test-runner\", resource=\"memory\"} / 1024 / 1024",
       "legendFormat": "Limit"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"remote-test-runner\"} / 1024 / 1024",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Test Runner Errors and Warnings",
     "type": "logs",
     "description": "Errors and Warnings found in Test Runner",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"} |~ \"WRN|ERR\""
      }
     ]
    },
    {
     "title": "Test Runner Info",
     "type": "logs",
     "description": "Info logs",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"} |= \"INF\""
      }
     ]
    },
    {
     "title": "Test Runner Debugs",
     "type": "logs",
     "description": "Debugs",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"} |~ \"DBG\""
      }
     ]
    }
   ]
  },
  {
   "title": "$cl_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "cl_node",
   "collapsed": true,
   "panels": [
    {
     "title": "Chainlink Node Logs",
     "type": "logs",
     "description": "All logs of the Chainlink node",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"}"
      }
     ]
    },
    {
     "title": "Chainlink Node Errors",
     "type": "logs",
     "description": "All [ERROR] logs from the Chainlink node.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"} | json | level=~\"error|crit\""
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Chainlink CPU usage and limit",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{container=\"node\", pod=\"$cl_node\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "description": "Chainlink RAM usage and limit",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{container=\"node\", pod=\"$cl_node\", resource=\"memory\"} / 1024 / 1024",
       "legendFormat": "Limits, container: {{container}} pod: {{pod}}"
      },
      {
       "expr": "container_memory_usage_bytes{container=\"node\", pod=\"$cl_node\"} / 1024 / 1024",
       "legendFormat": "Used, container: {{container}} pod: {{pod}}"
      }
     ]
    },
    {
     "title": "Chainlink Node Warnings",
     "type": "logs",
     "description": "All [WARN] logs from the Chainlink node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"}  | json | level=~\"warn\" | msg!=\"Disk space is not enough to log into disk any longer, required disk space\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mock Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mock Server Logs",
     "type": "logs",
     "description": "Logs of the mockserver",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"mockserver\"}"
      }
     ]
    },
    {
     "title": "Mock Server CPU",
     "type": "timeseries",
     "description": "Mock Server CPU usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{container=\"mockserver\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{container=\"mockserver\"}"
      }
     ]
    },
    {
     "title": "Mock Server RAM",
     "type": "timeseries",
     "description": "Mock Server RAM usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{container=\"mockserver\", resource=\"memory\"} / 1024 / 1024"
      },
      {
       "expr": "container_memory_usage_bytes{container=\"mockserver\"} / 1024 / 1024"
      }
     ]
    }
   ]
  },
  {
   "title": "$geth_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "geth_node",
   "collapsed": true,
   "panels": [
    {
     "title": "Geth Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=~\"geth-network|starknetdev\", pod=\"$geth_node\"}"
      }
     ]
    },
    {
     "title": "Geth CPU",
     "type": "timeseries",
     "description": "Geth CPU usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"geth-network\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=~\"geth-network|starknetdev\"}"
      }
     ]
    },
    {
     "title": "Geth RAM",
     "type": "timeseries",
     "description": "Geth RAM usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=~\"geth-network|starknetdev\", resource=\"memory\"} / 1024 / 1024"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=~\"geth-network|starknetdev\"} / 1024 / 1024"
      }
     ]
    }
   ]
  }
 ]
}