name: Go test
on:
  pull_request:
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a # v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Test
        run: nix develop -c make test
