name: Go test
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.7
        id: tool-versions
      - name: Set up Go ${{ steps.tool-versions.outputs.golang_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.tool-versions.outputs.golang_version }}
      - name: Test
        run: make test
