name: Publish Test Base Image
on:
  push:
    tags:
      - 'v*'

jobs:
  publish_test_base_image:
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: read
    env:
      BASE_IMAGE_TAG: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/test-base-image:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Base Image
        uses: smartcontractkit/chainlink-github-actions/docker/build-push@395ee22f09f3e975690fa150343ce1e0c9e908c3 # v2.2.10
        with:
          tags: ${{ env.BASE_IMAGE_TAG }}
          file: Dockerfile.base
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
